### ISSUE TITLE
Syntastic not detecting eslint

### ISSUE THREAD

**Issue by ezmiller** [mtscout6/syntastic-local-eslint.vim#12]
Hi, I have eslint installed locally in my project, and I've installed your plugin (using Vundle). But when I run vim (actually neovim) and then check `:SyntasticInfo`, it's not detecting any checkers:

> Syntastic version: 3.8.0-10 (Vim 704, Neovim, Darwin)
> Info for filetype:
> Global mode: active
> Filetype  is active
> The current file will be checked automatically
> Available checkers: -
> Currently enabled checkers: -
> The current file will not be checked (file not readable / not local)

Anyone have any idea why this might not be working?

**Comment by shofel** [comment]
What if you run `:SyntasticInfo javascript`?
Do you have something like `let g:syntastic_javascript_checkers = ['eslint']` in your `init.vim`?
Have you installed `eslint` global or local for the npm package?

**Comment by shofel** [comment]
@ezmiller Could you please provide some additional info if you still need any help
or consider closing the issue if it's not relevant any more?

**Comment by ezmiller** [comment]
This seems to be working for me now...so closing. The syntastic related settings I have in my `.vimrc` are:
```
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_loc_list_height = 5
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_javascript_checkers = ['eslint']
" let g:syntastic_debug = 3

let g:syntastic_error_symbol = '‼️'
let g:syntastic_style_error_symbol = '⁉️'
let g:syntastic_warning_symbol = '⚠️'
let g:syntastic_style_warning_symbol = '💩'

highlight link SyntasticErrorSign SignColumn
highlight link SyntasticWarningSign SignColumn
highlight link SyntasticStyleErrorSign SignColumn
highlight link SyntasticStyleWarningSign SignColumn
```
