### ISSUE TITLE
changes CWD when opening javascript file

### ISSUE THREAD

**Issue by jgallen23** [mtscout6/syntastic-local-eslint.vim#18]
I just grabbed the latest version of this plugin and now every time I open a js file, it updates the CWD to where the file is located.

**Comment by shofel** [comment]
Oops., it was me, who broken this with #16)))
@jgallen23, could you please review the code of #17? It reduces the time to lookup the local eslint executable, and has got no issue with local cwd.

**Comment by jgallen23** [comment]
I'm not sure I'm the best person to review this.  My vimscript is poor at best, I was just reporting the issue

**Comment by wjagodfrey** [comment]
This is a significant issue for me as well. Breaks my use of `fzf` and other things. Uninstalling for now.

**Comment by shofel** [comment]
@wjagodfrey, :disappointed: . Waiting for #17 to be merged.

**Comment by wjagodfrey** [comment]
That's fine. I will reinstall when this issue is resolved.

**Comment by shofel** [comment]
@jgallen23 @wjagodfrey Could you check out the issue is resolved in current master?

**Comment by wilfredjonathanjames** [comment]
Seems fixed, thanks @shofel

**Comment by L-P** [comment]
Can confirm, this is fixed.

**Comment by shofel** [comment]
@mtscout6, should we close this then?

P.S. I'd be so happy helping out to maintain the repo :whale2:

**Comment by jgallen23** [comment]
seems to be fixed, closing.
