### ISSUE TITLE
Installed via vundle on Ubuntu 16.04, error detected

### ISSUE THREAD

**Issue by jeromecovington** [mtscout6/syntastic-local-eslint.vim#3]
Any thoughts on the following?

```
"example.js" 46L, 1272C^[[2;2R^[]11;rgb:3030/0a0a/2424^G
Error detected while processing /home/example/.vim/bundle/syntastic-local-eslint.vim/ftplugin/javascript.vim:
line    1:
E484: Can't open file /tmp/vDWZDNV/4
Press ENTER or type command to continue
```

---

Thanks in advance!

**Comment by mtscout6** [comment]
By chance do you have ESLint installed either globally or to your local repo? My guess is that it's failing the system call to find the ESLint executable.

**Comment by jeromecovington** [comment]
Hm. I have it installed in my repo, and I just installed it globally to be doubly sure, but I continue to see the "Error detected" message when I start vim.

**Comment by jeromecovington** [comment]
Additional information is that I am using nvm to manage my node versions.

**Comment by jeromecovington** [comment]
Am using fish as my shell. Do you think this line might be the problem? - https://github.com/mtscout6/syntastic-local-eslint.vim/blob/master/ftplugin/javascript.vim#L1

Fish sets and exports system variables differently than bash. Oddly though this has not been an issue for me on MacOSX (also running fish as default shell).

**Comment by mtscout6** [comment]
That's the line that seems to be the offender, but I can't see how. It's definitely something system specific.

**Comment by shofel** [comment]
Fish doesn't support `&&` syntax [by design](https://github.com/fish-shell/fish-shell/issues/150)
That is why command [`PATH=$(npm bin):$PATH && which eslint`](https://github.com/mtscout6/syntastic-local-eslint.vim/blob/master/ftplugin/javascript.vim#L3) fails
