### ISSUE TITLE
Slow buffer switching on first load

### ISSUE THREAD

**Issue by iryan2** [mtscout6/syntastic-local-eslint.vim#4]
If I do 
`$ vim foo.js bar.js`

with this plugin enabled, it takes about 1 second longer to display the contents of foo.js than if this plugin is disabled. Then, when I `:bnext` open the other buffer, it takes another full second before it is displayed. 

Once vim has displayed the contents of each buffer, it's fast to switch between them again, it just seems like something's happening upon the initial display of any given buffer.

Any idea what's causing this, and/or if it's possible to speed up?

Thanks for the plugin btw :)

**Comment by mtscout6** [comment]
That doesn't surprise me. Considering on every buffer vim is checking to see where the closest eslint executable is to the underlying file for that buffer. That does take about a second. I'd be open to any pull request that would make that faster. I have noticed that vim slowed down for me a few months ago, but I was changing a lot of things at the time and never took the time to pinpoint the cause.

**Comment by mtscout6** [comment]
This line is the culprit in specific: https://github.com/mtscout6/syntastic-local-eslint.vim/blob/master/ftplugin/javascript.vim#L1

**Comment by iryan2** [comment]
Okay thanks for the info, I suppose I'll just close this one.
